//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CustomObjectInfo_.h
//  Source: ssafy_msgs\msg\CustomObjectInfo_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _CUSTOMOBJECTINFO__H_
#define _CUSTOMOBJECTINFO__H_

#include "sacpp_mapping.h"
#include "geometry_msgs/msg/dds_opensplice/Vector3_.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct CustomObjectInfo_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_
         {
               struct _position__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < ::geometry_msgs::msg::dds_::Vector3_, struct _position__seq_uniq_> _position__seq;
               typedef DDS_DCPSSequence_var < _position__seq> _position__seq_var;
               typedef DDS_DCPSSequence_out < _position__seq> _position__seq_out;
               _position__seq position_;
         };

         typedef DDS_DCPSStruct_var < CustomObjectInfo_> CustomObjectInfo__var;
         typedef DDS_DCPSStruct_out < CustomObjectInfo_> CustomObjectInfo__out;
      }
   }
}




#endif
