//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CustomObjectInfo_Dcps.h
//  Source: ssafy_msgs\msg\CustomObjectInfo_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _CUSTOMOBJECTINFO_DCPS_H_
#define _CUSTOMOBJECTINFO_DCPS_H_

#include "sacpp_mapping.h"
#include "CustomObjectInfo_.h"
#include "dds_dcps.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_TypeSupportInterface;

         typedef CustomObjectInfo_TypeSupportInterface * CustomObjectInfo_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < CustomObjectInfo_TypeSupportInterface> CustomObjectInfo_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < CustomObjectInfo_TypeSupportInterface> CustomObjectInfo_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataWriter;

         typedef CustomObjectInfo_DataWriter * CustomObjectInfo_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < CustomObjectInfo_DataWriter> CustomObjectInfo_DataWriter_var;
         typedef DDS_DCPSInterface_out < CustomObjectInfo_DataWriter> CustomObjectInfo_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataReader;

         typedef CustomObjectInfo_DataReader * CustomObjectInfo_DataReader_ptr;
         typedef DDS_DCPSInterface_var < CustomObjectInfo_DataReader> CustomObjectInfo_DataReader_var;
         typedef DDS_DCPSInterface_out < CustomObjectInfo_DataReader> CustomObjectInfo_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataReaderView;

         typedef CustomObjectInfo_DataReaderView * CustomObjectInfo_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < CustomObjectInfo_DataReaderView> CustomObjectInfo_DataReaderView_var;
         typedef DDS_DCPSInterface_out < CustomObjectInfo_DataReaderView> CustomObjectInfo_DataReaderView_out;

         struct CustomObjectInfo_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < CustomObjectInfo_, struct CustomObjectInfo_Seq_uniq_> CustomObjectInfo_Seq;
         typedef DDS_DCPSSequence_var < CustomObjectInfo_Seq> CustomObjectInfo_Seq_var;
         typedef DDS_DCPSSequence_out < CustomObjectInfo_Seq> CustomObjectInfo_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef CustomObjectInfo_TypeSupportInterface_ptr _ptr_type;
            typedef CustomObjectInfo_TypeSupportInterface_var _var_type;

            static CustomObjectInfo_TypeSupportInterface_ptr _duplicate (CustomObjectInfo_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static CustomObjectInfo_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            CustomObjectInfo_TypeSupportInterface_ptr _this () { return this; }


         protected:
            CustomObjectInfo_TypeSupportInterface () {};
            ~CustomObjectInfo_TypeSupportInterface () {};
         private:
            CustomObjectInfo_TypeSupportInterface (const CustomObjectInfo_TypeSupportInterface &);
            CustomObjectInfo_TypeSupportInterface & operator = (const CustomObjectInfo_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef CustomObjectInfo_DataWriter_ptr _ptr_type;
            typedef CustomObjectInfo_DataWriter_var _var_type;

            static CustomObjectInfo_DataWriter_ptr _duplicate (CustomObjectInfo_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static CustomObjectInfo_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            CustomObjectInfo_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const CustomObjectInfo_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const CustomObjectInfo_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const CustomObjectInfo_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const CustomObjectInfo_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const CustomObjectInfo_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const CustomObjectInfo_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const CustomObjectInfo_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const CustomObjectInfo_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const CustomObjectInfo_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const CustomObjectInfo_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (CustomObjectInfo_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const CustomObjectInfo_& instance_data) = 0;

         protected:
            CustomObjectInfo_DataWriter () {};
            ~CustomObjectInfo_DataWriter () {};
         private:
            CustomObjectInfo_DataWriter (const CustomObjectInfo_DataWriter &);
            CustomObjectInfo_DataWriter & operator = (const CustomObjectInfo_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef CustomObjectInfo_DataReader_ptr _ptr_type;
            typedef CustomObjectInfo_DataReader_var _var_type;

            static CustomObjectInfo_DataReader_ptr _duplicate (CustomObjectInfo_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static CustomObjectInfo_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            CustomObjectInfo_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (CustomObjectInfo_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (CustomObjectInfo_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (CustomObjectInfo_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const CustomObjectInfo_& instance) = 0;

         protected:
            CustomObjectInfo_DataReader () {};
            ~CustomObjectInfo_DataReader () {};
         private:
            CustomObjectInfo_DataReader (const CustomObjectInfo_DataReader &);
            CustomObjectInfo_DataReader & operator = (const CustomObjectInfo_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs CustomObjectInfo_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef CustomObjectInfo_DataReaderView_ptr _ptr_type;
            typedef CustomObjectInfo_DataReaderView_var _var_type;

            static CustomObjectInfo_DataReaderView_ptr _duplicate (CustomObjectInfo_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static CustomObjectInfo_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static CustomObjectInfo_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            CustomObjectInfo_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (CustomObjectInfo_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (CustomObjectInfo_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (CustomObjectInfo_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (CustomObjectInfo_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const CustomObjectInfo_& instance) = 0;

         protected:
            CustomObjectInfo_DataReaderView () {};
            ~CustomObjectInfo_DataReaderView () {};
         private:
            CustomObjectInfo_DataReaderView (const CustomObjectInfo_DataReaderView &);
            CustomObjectInfo_DataReaderView & operator = (const CustomObjectInfo_DataReaderView &);
         };

      }
   }
}




#endif
