//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: EnviromentStatus_.h
//  Source: ssafy_msgs\msg\EnviromentStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _ENVIROMENTSTATUS__H_
#define _ENVIROMENTSTATUS__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct EnviromentStatus_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs EnviromentStatus_
         {
               DDS::Octet month_;
               DDS::Octet day_;
               DDS::Octet hour_;
               DDS::Octet minute_;
               DDS::Octet temperature_;
               DDS::String_mgr weather_;
         };

         typedef DDS_DCPSStruct_var < EnviromentStatus_> EnviromentStatus__var;
         typedef DDS_DCPSStruct_out < EnviromentStatus_> EnviromentStatus__out;
      }
   }
}




#endif
