//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HandControl_.h
//  Source: ssafy_msgs\msg\HandControl_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _HANDCONTROL__H_
#define _HANDCONTROL__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct HandControl_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs HandControl_
         {
               DDS::Octet control_mode_;
               DDS::Float put_distance_;
               DDS::Float put_height_;
         };

         typedef DDS_DCPSStruct_var < HandControl_> HandControl__var;
         typedef HandControl_&HandControl__out;
      }
   }
}




#endif
