//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ObjectInfo_.h
//  Source: ssafy_msgs\msg\ObjectInfo_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _OBJECTINFO__H_
#define _OBJECTINFO__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct ObjectInfo_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs ObjectInfo_
         {
               struct _idx_obj__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Short, struct _idx_obj__seq_uniq_> _idx_obj__seq;
               typedef DDS_DCPSSequence_var < _idx_obj__seq> _idx_obj__seq_var;
               typedef DDS_DCPSSequence_out < _idx_obj__seq> _idx_obj__seq_out;
               struct _x__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Float, struct _x__seq_uniq_> _x__seq;
               typedef DDS_DCPSSequence_var < _x__seq> _x__seq_var;
               typedef DDS_DCPSSequence_out < _x__seq> _x__seq_out;
               struct _y__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Float, struct _y__seq_uniq_> _y__seq;
               typedef DDS_DCPSSequence_var < _y__seq> _y__seq_var;
               typedef DDS_DCPSSequence_out < _y__seq> _y__seq_out;
               DDS::Short num_obj_;
               _idx_obj__seq idx_obj_;
               _x__seq x_;
               _y__seq y_;
         };

         typedef DDS_DCPSStruct_var < ObjectInfo_> ObjectInfo__var;
         typedef DDS_DCPSStruct_out < ObjectInfo_> ObjectInfo__out;
      }
   }
}




#endif
