//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TurtlebotStatus_Dcps.h
//  Source: ssafy_msgs\msg\TurtlebotStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _TURTLEBOTSTATUS_DCPS_H_
#define _TURTLEBOTSTATUS_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "TurtlebotStatus_.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_TypeSupportInterface;

         typedef TurtlebotStatus_TypeSupportInterface * TurtlebotStatus_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < TurtlebotStatus_TypeSupportInterface> TurtlebotStatus_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < TurtlebotStatus_TypeSupportInterface> TurtlebotStatus_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataWriter;

         typedef TurtlebotStatus_DataWriter * TurtlebotStatus_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < TurtlebotStatus_DataWriter> TurtlebotStatus_DataWriter_var;
         typedef DDS_DCPSInterface_out < TurtlebotStatus_DataWriter> TurtlebotStatus_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataReader;

         typedef TurtlebotStatus_DataReader * TurtlebotStatus_DataReader_ptr;
         typedef DDS_DCPSInterface_var < TurtlebotStatus_DataReader> TurtlebotStatus_DataReader_var;
         typedef DDS_DCPSInterface_out < TurtlebotStatus_DataReader> TurtlebotStatus_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataReaderView;

         typedef TurtlebotStatus_DataReaderView * TurtlebotStatus_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < TurtlebotStatus_DataReaderView> TurtlebotStatus_DataReaderView_var;
         typedef DDS_DCPSInterface_out < TurtlebotStatus_DataReaderView> TurtlebotStatus_DataReaderView_out;

         struct TurtlebotStatus_Seq_uniq_ {};
         typedef DDS_DCPSUFLSeq < TurtlebotStatus_, struct TurtlebotStatus_Seq_uniq_> TurtlebotStatus_Seq;
         typedef DDS_DCPSSequence_var < TurtlebotStatus_Seq> TurtlebotStatus_Seq_var;
         typedef DDS_DCPSSequence_out < TurtlebotStatus_Seq> TurtlebotStatus_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef TurtlebotStatus_TypeSupportInterface_ptr _ptr_type;
            typedef TurtlebotStatus_TypeSupportInterface_var _var_type;

            static TurtlebotStatus_TypeSupportInterface_ptr _duplicate (TurtlebotStatus_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static TurtlebotStatus_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            TurtlebotStatus_TypeSupportInterface_ptr _this () { return this; }


         protected:
            TurtlebotStatus_TypeSupportInterface () {};
            ~TurtlebotStatus_TypeSupportInterface () {};
         private:
            TurtlebotStatus_TypeSupportInterface (const TurtlebotStatus_TypeSupportInterface &);
            TurtlebotStatus_TypeSupportInterface & operator = (const TurtlebotStatus_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef TurtlebotStatus_DataWriter_ptr _ptr_type;
            typedef TurtlebotStatus_DataWriter_var _var_type;

            static TurtlebotStatus_DataWriter_ptr _duplicate (TurtlebotStatus_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static TurtlebotStatus_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            TurtlebotStatus_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const TurtlebotStatus_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const TurtlebotStatus_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const TurtlebotStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const TurtlebotStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const TurtlebotStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const TurtlebotStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const TurtlebotStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const TurtlebotStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const TurtlebotStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const TurtlebotStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (TurtlebotStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const TurtlebotStatus_& instance_data) = 0;

         protected:
            TurtlebotStatus_DataWriter () {};
            ~TurtlebotStatus_DataWriter () {};
         private:
            TurtlebotStatus_DataWriter (const TurtlebotStatus_DataWriter &);
            TurtlebotStatus_DataWriter & operator = (const TurtlebotStatus_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef TurtlebotStatus_DataReader_ptr _ptr_type;
            typedef TurtlebotStatus_DataReader_var _var_type;

            static TurtlebotStatus_DataReader_ptr _duplicate (TurtlebotStatus_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static TurtlebotStatus_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            TurtlebotStatus_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (TurtlebotStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (TurtlebotStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (TurtlebotStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const TurtlebotStatus_& instance) = 0;

         protected:
            TurtlebotStatus_DataReader () {};
            ~TurtlebotStatus_DataReader () {};
         private:
            TurtlebotStatus_DataReader (const TurtlebotStatus_DataReader &);
            TurtlebotStatus_DataReader & operator = (const TurtlebotStatus_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef TurtlebotStatus_DataReaderView_ptr _ptr_type;
            typedef TurtlebotStatus_DataReaderView_var _var_type;

            static TurtlebotStatus_DataReaderView_ptr _duplicate (TurtlebotStatus_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static TurtlebotStatus_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static TurtlebotStatus_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            TurtlebotStatus_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (TurtlebotStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (TurtlebotStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (TurtlebotStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (TurtlebotStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const TurtlebotStatus_& instance) = 0;

         protected:
            TurtlebotStatus_DataReaderView () {};
            ~TurtlebotStatus_DataReaderView () {};
         private:
            TurtlebotStatus_DataReaderView (const TurtlebotStatus_DataReaderView &);
            TurtlebotStatus_DataReaderView & operator = (const TurtlebotStatus_DataReaderView &);
         };

      }
   }
}




#endif
