//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TurtlebotStatus_.h
//  Source: ssafy_msgs\msg\TurtlebotStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _TURTLEBOTSTATUS__H_
#define _TURTLEBOTSTATUS__H_

#include "sacpp_mapping.h"
#include "geometry_msgs/msg/dds_opensplice/Twist_.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct TurtlebotStatus_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TurtlebotStatus_
         {
               ::geometry_msgs::msg::dds_::Twist_ twist_;
               DDS::Octet power_supply_status_;
               DDS::Float battery_percentage_;
               DDS::Boolean can_use_hand_;
               DDS::Boolean can_put_;
               DDS::Boolean can_lift_;
         };

         typedef DDS_DCPSStruct_var < TurtlebotStatus_> TurtlebotStatus__var;
         typedef TurtlebotStatus_&TurtlebotStatus__out;
      }
   }
}




#endif
